# Generated by Django 4.2.1 on 2023-07-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
        ('productos', '0002_alter_producto_options_remove_producto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_de_entrega',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodo_de_pago')),
            ],
            options={
                'verbose_name': 'Nota_de_entrega',
                'verbose_name_plural': 'Notas_de_entregas',
                'db_table': 'Nota_de_entrega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('igtf', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodo_de_pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
                'ordering': ['codigo'],
            },
        ),
    ]
