# Generated by Django 4.2.1 on 2023-07-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Producto',
            fields=[
                ('categoria', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria_Producto',
                'verbose_name_plural': 'Categorias_Productos',
                'db_table': 'Categoria_Producto',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fecha_de_vencimiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('exento', models.BooleanField(blank=True, null=True)),
                ('imagen_de_producto', models.ImageField(blank=True, null=True, upload_to='img_product', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MN_Subcategoria_Producto',
            fields=[
                ('subcategoria', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria_producto')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Subcategoria_Producto',
                'verbose_name_plural': 'Subcategorias_Productos',
                'db_table': 'Subcategoria_Producto',
                'ordering': ['subcategoria'],
            },
        ),
    ]
