# Generated by Django 4.2.1 on 2023-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('producto', models.CharField(max_length=150, verbose_name='Producto')),
                ('fecha_de_vencimiento', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('imagen_de_producto', models.ImageField(blank=True, null=True, upload_to='img_product', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
    ]
