# Generated by Django 4.2.2 on 2023-07-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_exento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='exento',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
