# Generated by Django 4.2.1 on 2023-07-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre_Cliente',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=200)),
                ('segundo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('primer_apellido', models.CharField(max_length=200)),
                ('segundo_apellido', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Nombre_Cliente',
                'verbose_name_plural': 'Nombres_Clientes',
                'db_table': 'Nombre_Cliente',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=500)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.nombre_cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
    ]
