# Generated by Django 4.2.1 on 2023-07-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombre_cliente',
            options={'ordering': ['cedula'], 'verbose_name': 'Nombre_Cliente', 'verbose_name_plural': 'Nombres_Clientes'},
        ),
        migrations.AlterModelTable(
            name='nombre_cliente',
            table='Nombre_Cliente',
        ),
    ]
