# Generated by Django 4.2.1 on 2023-07-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_de_compra', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('inversion', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nombre_Supervisor',
            fields=[
                ('cedula', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=200)),
                ('segundo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('primer_apellido', models.CharField(max_length=200)),
                ('segundo_apellido', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Nombre_Supervisor',
                'verbose_name_plural': 'Nombres_Supervisores',
                'db_table': 'Nombre_Supervisor',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='MN_Compra_Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'MN_Compra_Proveedor',
                'verbose_name_plural': 'MN_Compra_Proveedor',
                'db_table': 'MN_Compra_Proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MN_Compra_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'MN_Compra_Producto',
                'verbose_name_plural': 'MN_Compras_Productos',
                'db_table': 'MN_Compra_Producto',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='supervisor_cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.nombre_supervisor', verbose_name='Supervisor_Cedula'),
        ),
    ]
