# Generated by Django 4.2.1 on 2023-07-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_producto_options_remove_producto_id_and_more'),
        ('proveedores', '0003_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('fecha_de_compra', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('supervisor', models.CharField(max_length=500, verbose_name='Supervisor')),
                ('inversion', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compras',
                'verbose_name_plural': 'Compra',
                'db_table': 'Compra',
                'ordering': ['id'],
            },
        ),
    ]
