# Generated by Django 4.2.2 on 2023-07-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='inversion',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Valor_Unitario'),
        ),
    ]
