# Generated by Django 4.2.1 on 2023-07-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
