# Generated by Django 4.2.2 on 2023-07-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('compras', '0002_remove_compra_inversion_compra_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'db_table': 'Supervisor',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='mn_compra_proveedor',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='mn_compra_proveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='supervisor_cedula',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_de_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MN_Compra_Producto',
        ),
        migrations.DeleteModel(
            name='MN_Compra_Proveedor',
        ),
        migrations.DeleteModel(
            name='Nombre_Supervisor',
        ),
        migrations.AddField(
            model_name='compra',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.supervisor'),
            preserve_default=False,
        ),
    ]
