# Generated by Django 4.2.2 on 2023-07-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_supervisor_remove_mn_compra_proveedor_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='supervisor',
        ),
    ]
