# Generated by Django 4.2.1 on 2023-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rif', models.CharField(default=0, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Proveedor')),
                ('razon_social', models.CharField(max_length=500, verbose_name='Razon Social')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
                'ordering': ['rif'],
            },
        ),
    ]
