# Generated by Django 4.2.1 on 2023-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('proveedor', models.CharField(max_length=300, verbose_name='Proveedor')),
                ('razon_social', models.CharField(max_length=500, verbose_name='Razon Social')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion')),
            ],
        ),
    ]
