# Generated by Django 4.2.1 on 2023-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_options_alter_proveedor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['rif'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rif',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
